# config/packages/security.yaml
security:
    # Configuration des encodeurs de mot de passe
    password_hashers:
        App\Entity\User: 'auto'  # Utilisation du mot de passe hashé selon le format recommandé par Symfony (bcrypt ou argon2i)

    # Définition des providers d'utilisateur (ici en base de données avec Doctrine)
    providers:
        users_in_database:
            entity:
                class: App\Entity\User
                property: email  # Utiliser l'email pour se connecter, changez-le si vous utilisez un autre champ

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
