vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        movie_images:
            uri_prefix: /images/movies
            upload_destination: '%kernel.project_dir%/public/images/movies'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

